### ISSUE TITLE
Player Stats/Stat Messages

### ISSUE THREAD

**Issue by sperniciaro** [cse-southeast-devcrew/microsoft-teams-bot-food-fite#51]
# Stats and Messages

## Description 
As a player I want to be able to view my health status and game status

## Acceptance Criteria 
Each player will be able to see their stat information as part of the following alerts (for the following events):

#### Stats
* [x] Gear health
* [x] Food inventory (quantity)
* [x] Player's health
* [ ] Number of players remaining in game

#### Stat Alert Events
* [ ] When a player enters the game (all stats 1-4)
* [ ] At the start of the fight (stats 1-3)
* [ ] After a throw (stats 1-3)
* [ ] After a miss (stats 1-3)
* [ ] After a hit (stats 1-3)
* [ ] After a win (all stats 1-4)

**Comment by jamesptruitt** [comment]
Added Status Card
